[package]
name = "demo"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.1"
dioxus = "0.6.3"
dioxus-ssr = "0.6.2"
reqwest = "0.12.15"
tokio = { version = "1.44.1", features = ["full"] }
tower-http = { version = "0.6.2", features = ["fs"] }

[[bin]]
name = "ssr"
path = "src/ssr.rs"
